### ISSUE TITLE
[Federator] Bad request error (and others) on WFCatalog queries

### ISSUE THREAD

**Issue by jppzanetti** [EIDA/userfeedback#185]
**Describe the problem**
I'm getting the following error when querying the `wfcatalog` service of the Federator:

```
Error 400: Bad request

{'stream_epochs': {0: {'endtime': ['Not a valid datetime.']}, 1: {'endtime': ['Not a valid datetime.']}, 2: {'endtime': ['Not a valid datetime.']}, 3: {'endtime': ['Not a valid datetime.']}}}

Usage details are available from http://www.fdsn.org/webservices/

Request:
https://eida-federator.ethz.ch/fedws/wfcatalog/json/1/query?include=sample&net=GE&sta=SALP&start=2010-01-01&end=2015-31-01&cha=?N?,HG?,?H?,?DF

Request Submitted:
2025-08-26T12:10:50.684900

Service version:
0.12.1
```

**To Reproduce**
Queries were/can be made either through the [EIDA Data Availability page](https://www.orfeus-eu.org/data/eida/quality/availability/), or with `curl`, for example:

```
curl -kv "https://eida-federator.ethz.ch/eidaws/wfcatalog/1/query?include=sample&net=GE&sta=SALP&start=2020-01-01&end=2020-31-12&cha=?N?,HG?,?H?,?DF"
```

**Screenshots**
See above.

**Client**
See above.

**Comment by sheimers** [comment]
Hello João,

You swapped the day and the month. 2020-31-12 should be 2020-12-31.

Then I get "HTTP/1.1 204 No Content", but no error.

It works for other networks, eg. FR:

`curl -kv "https://eida-federator.ethz.ch/eidaws/wfcatalog/1/query?include=sample&net=FR&sta=OG35&start=2020-01-01&end=2020-12-31&cha=?N?,HG?,?H?,?DF"`


But a direct request to GFZ works, there is definitely a problem with the federator.

`curl -kv "http://geofon.gfz.de/eidaws/wfcatalog/1/query?include=sample&net=GE&sta=SALP&start=2020-01-01&end=2020-12-31&cha=?N?,HG?,?H?,?DF"`

**Comment by sheimers** [comment]
Now some minutes later, the original query with the date corrected works:


`heimers@foehr:/tmp$ curl -kv "https://eida-federator.ethz.ch/eidaws/wfcatalog/1/query?include=sample&net=GE&sta=SALP&start=2020-01-01&end=2020-12-31&cha=?N?,HG?,?H?,?DF" 1>/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host eida-federator.ethz.ch:443 was resolved.
* IPv6: (none)
* IPv4: 129.132.148.115
*   Trying 129.132.148.115:443...
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [1577 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [112 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2081 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384 / x25519 / RSASSA-PSS
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=CH; ST=Zuerich; L=Zuerich; O=ETH Zuerich; CN=eida-federator.ethz.ch
*  start date: Feb  4 17:35:55 2022 GMT
*  expire date: Feb  4 17:45:00 2023 GMT
*  issuer: C=NL; O=QuoVadis Trustlink B.V.; CN=QuoVadis Europe SSL CA G2
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to eida-federator.ethz.ch (129.132.148.115) port 443
* using HTTP/1.x
} [5 bytes data]
> GET /eidaws/wfcatalog/1/query?include=sample&net=GE&sta=SALP&start=2020-01-01&end=2020-12-31&cha=?N?,HG?,?H?,?DF HTTP/1.1
> Host: eida-federator.ethz.ch
> User-Agent: curl/8.14.1
> Accept: */*
> 
* Request completely sent off
{ [5 bytes data]
< HTTP/1.1 200 OK
< Server: nginx/1.18.0 (Ubuntu)
< Date: Mon, 08 Sep 2025 12:12:44 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Content-Disposition: attachment; filename="eidaws-federator-2025-09-08T12:12:44.716774.json"
< 
{ [6 bytes data]
100 3057k    0 3057k    0     0  3734k      0 --:--:-- --:--:-- --:--:-- 3733k
* Connection #0 to host eida-federator.ethz.ch left intact
`

**Comment by jppzanetti** [comment]
> You swapped the day and the month. 2020-31-12 should be 2020-12-31.

Oh well, that's embarrassing 🤦.

My original issue was probably the 204, and while testing it out I mistyped the date, and fell into the wrong rabbit hole. However, the wrong 204 still happens on my original case:

This request directly to ODC returns 200 and a lot of data:

```
curl -kv "https://orfeus-eu.org/eidaws/wfcatalog/1/query?include=sample&net=NL&sta=L311&start=2020-01-01&end=2022-12-31&cha=?N?,HG?,?H?,?DF"
```

While going through the Federator returns a 204:

```
curl -kv "https://federator.orfeus-eu.org/eidaws/wfcatalog/1/query?include=sample&net=NL&sta=L311&start=2020-01-01&end=2022-12-31&cha=?N?,HG?,?H?,?DF"
```

**Comment by petrrr** [comment]
Hi @all! 
Please note that apparently all Federator requests to ODC are currently failing.
This should explain this one.

See also https://github.com/EIDA/etc/issues/93

**Comment by kaestli** [comment]
solution to the general federator/ODC issue at: https://github.com/EIDA/etc/issues/93
